[package]
name = "declarative"
version = "0.1.0"
authors = ["Christopher Breeden <github@u.breeden.cc>"]

[dependencies]
byteorder = "*"
declarative-macros = { path = "declarative_macros", version = "*" }
